WebApp/Controllers/CaesarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApp.Data;
using WebApp.Models;
using WebApp.Roles;
using WebApp.ViewModels;

namespace WebApp.Controllers
{
    [Authorize]
    public class CaesarsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IServiceProvider _serviceProvider;
        private readonly UserManager<AppUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        
        public CaesarsController(ApplicationDbContext context, IServiceProvider serviceProvider, UserManager<AppUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _context = context;
            _serviceProvider = serviceProvider;
            _roleManager = roleManager;
            _userManager = userManager;
            
        }

        
        // GET: Caesars
        // See data only for the current user
        public async Task<IActionResult> Index()
        {
            CreateRoles.CreateCaesarAdmin(_serviceProvider, _userManager, _roleManager).Wait();

            
            
            var res = await _context
                .Caesars
                .Where(c => c.AppUserId == GetUserId())
                .Select(c => new CaesarIndexViewModel()
                {
                    Id = c.Id,
                    Key = c.Key,
                    EncryptedText = c.EncryptedText, 
                })
                .ToListAsync();
                
            return View(res);
        }

        
        // GET: Caesars/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var caesar = await _context.Caesars
                .Include(c => c.AppUser)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (caesar == null)
            {
                return NotFound();
            }
            
            var caesarVM = new CaesarIndexViewModel
            {
                Id = caesar.Id,
                Key = caesar.Key,
                EncryptedText = caesar.EncryptedText,
            };

            return View(caesarVM);
        }

        
        // GET: Caesars/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Caesars/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CaesarCreateViewModel caesarVM)
        {
            // now we cannot use anymore direct models
            if (ModelState.IsValid)
            {
                var caesar = new Caesar()
                {
                    Key = caesarVM.Key,
                    EncryptedText = caesarVM.EncryptedText,
                    AppUserId = GetUserId(),
                };
                _context.Add(caesar);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(caesarVM);
        }

        // Gets user id
        public string GetUserId()
        {
            return User.Claims.First(c => c.Type == ClaimTypes.NameIdentifier).Value;
        }
        
        
        [Authorize(Roles = Roles.Roles.AdminCaesar)]
        // GET: Caesars/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var caesar = await _context.Caesars.FindAsync(id);
            if (caesar == null)
            {
                return NotFound();
            }

            var caesarVM = new CaesarIndexViewModel
            {
                Id = caesar.Id,
                Key = caesar.Key,
                EncryptedText = caesar.EncryptedText,
            };
            
            return View(caesarVM);
        }

        [Authorize(Roles = Roles.Roles.AdminCaesar)]
        // POST: Caesars/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, CaesarIndexViewModel caesarVM)
        {
            if (id != caesarVM.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var caesar = await _context.Caesars.FindAsync(id);
                    if (caesar == null)
                    {
                        return NotFound();
                    }
                    caesar.Key = caesarVM.Key;
                    caesar.EncryptedText = caesarVM.EncryptedText;
                    _context.Update(caesar);
                    await _context.SaveChangesAsync();
                    
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CaesarExists(id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
            }
            return View(caesarVM);
        }

        [Authorize(Roles = Roles.Roles.AdminCaesar)]
        // GET: Caesars/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var caesar = await _context.Caesars
                .Include(c => c.AppUser)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (caesar == null)
            {
                return NotFound();
            }

            var caesarVM = new CaesarIndexViewModel
            {
                Id = caesar.Id,
                Key = caesar.Key,
                EncryptedText = caesar.EncryptedText,
            };
            
            return View(caesarVM);
        }

        [Authorize(Roles = Roles.Roles.AdminCaesar)]
        // POST: Caesars/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var caesar = await _context.Caesars.FindAsync(id);
            if (caesar != null)
            {
                _context.Caesars.Remove(caesar);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CaesarExists(Guid id)
        {
          return (_context.Caesars?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
    
}

WebApp/Controllers/VigeneresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApp.Data;
using WebApp.Models;
using WebApp.Roles;
using WebApp.ViewModels;

namespace WebApp.Controllers
{
    [Authorize]
    
    public class VigeneresController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IServiceProvider _serviceProvider;
        private readonly UserManager<AppUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public VigeneresController(ApplicationDbContext context, IServiceProvider serviceProvider, UserManager<AppUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            _context = context;
            _serviceProvider = serviceProvider;
            _userManager = userManager;
            _roleManager = roleManager;
        }


        // GET: Vigeneres
        // See data only for the current user
        public async Task<IActionResult> Index()
        {
            CreateRoles.CreateVigenereAdmin(_serviceProvider, _userManager, _roleManager).Wait();

            
            
            var res = await _context
                .Vigeneres
                .Where(v => v.AppUserId == GetUserId())
                .Select(v => new VigenereIndexViewModel()
                {
                    Id = v.Id,
                    Key = v.Key,
                    EncryptedText = v.EncryptedText,
                })
                .ToListAsync();
            
            return View(res);
        }

        
        // GET: Vigeneres/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vigenere = await _context.Vigeneres
                .Include(v => v.AppUser)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (vigenere == null)
            {
                return NotFound();
            }

            var vigenereVM = new VigenereIndexViewModel
            {
                Id = vigenere.Id,
                Key = vigenere.Key,
                EncryptedText = vigenere.EncryptedText,
            };
            
            return View(vigenereVM);
        }

        // GET: Vigeneres/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Vigeneres/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(VigenereCreateViewModel vigenereVM)
        {
            // cannot use anymore direct models
            if (ModelState.IsValid)
            {
                var vigenere = new Vigenere()
                {
                    Key = vigenereVM.Key,
                    EncryptedText = vigenereVM.EncryptedText,
                    AppUserId = GetUserId(),

                };
                _context.Add(vigenere);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(vigenereVM);
        }

        
        // Gets user id
        public string GetUserId()
        {
            return User.Claims.First(v => v.Type == ClaimTypes.NameIdentifier).Value;
        }
        
        
        
        // GET: Vigeneres/Edit/5
        [Authorize(Roles = Roles.Roles.AdminVigenere)]
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vigenere = await _context.Vigeneres.FindAsync(id);
            if (vigenere == null)
            {
                return NotFound();
            }
            
            var vigenereVM = new VigenereIndexViewModel
            {
                Id = vigenere.Id,
                Key = vigenere.Key,
                EncryptedText = vigenere.EncryptedText,
            };
            
            return View(vigenereVM);
        }

        
        // POST: Vigeneres/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = Roles.Roles.AdminVigenere)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, VigenereIndexViewModel vigenereVM)
        {
            if (id != vigenereVM.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var vigenere = await _context.Vigeneres.FindAsync(id);
                    if (vigenere == null)
                    {
                        return NotFound();
                    }
                    vigenere.Key = vigenereVM.Key;
                    vigenere.EncryptedText = vigenereVM.EncryptedText;
                    _context.Update(vigenere);
                    await _context.SaveChangesAsync();
                    
                    return RedirectToAction(nameof(Index));              
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VigenereExists(id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
            }
            return View(vigenereVM);
        }

        
        // GET: Vigeneres/Delete/5
        [Authorize(Roles = Roles.Roles.AdminVigenere)]
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vigenere = await _context.Vigeneres
                .Include(v => v.AppUser)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (vigenere == null)
            {
                return NotFound();
            }

            var vigenereVM = new VigenereIndexViewModel
            {
                Id = vigenere.Id,
                Key = vigenere.Key,
                EncryptedText = vigenere.EncryptedText,
            };
            
            return View(vigenereVM);
        }

        
        // POST: Vigeneres/Delete/5
        [Authorize(Roles = Roles.Roles.AdminVigenere)]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {

            var vigenere = await _context.Vigeneres.FindAsync(id);
            if (vigenere != null)
            {
                _context.Vigeneres.Remove(vigenere);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VigenereExists(Guid id)
        {
          return (_context.Vigeneres?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

WebApp/Views/Shared/_Layout.cshtml
@using WebApp.Roles
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/WebApp.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApp</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    
                    @if (!User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Caesars" asp-action="Index">Encryption Storage</a>
                        </li> 
                    }
                    
                    @if (!User.IsInRole(Roles.AdminCaesar) && !User.IsInRole(Roles.AdminVigenere) && User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Caesars" asp-action="Index">My Caesar</a>
                        </li>  
                            
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Vigeneres" asp-action="Index">My Vigenere</a>
                        </li>
                    }
                    
                    @if (User.IsInRole(Roles.AdminCaesar) && !User.IsInRole(Roles.AdminVigenere))
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Caesars" asp-action="Index">Caesar's Personal Caesar</a>
                        </li> 
                            
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AdminCaesars" asp-action="Index">All_Caesars</a>
                        </li> 
                            
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Vigeneres" asp-action="Index">Vigenere (!monitored by another admin!)</a>
                        </li>
                    }
                    
                     @if (User.IsInRole(Roles.AdminVigenere) && !User.IsInRole(Roles.AdminCaesar))
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Vigeneres" asp-action="Index">Vigenere's Personal Vigenere</a>
                        </li> 
                            
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AdminVigeneres" asp-action="Index">All_Vigeneres</a>
                        </li> 
                            
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Caesars" asp-action="Index">Caesar (!monitored by another admin!)</a>
                        </li>
                    }
                    
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                    </li>  
                </ul>
                <partial name="_LoginPartial"/>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2023 - WebApp - <a asp-area="" asp-controller="Home" asp-action="About">About</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>